import type { VercelRequest, VercelResponse } from '@vercel/node';
const wishlist = [
  {
    id: 'fe0296f8-6764-474d-b1df-f694dc09da7f',
    name: 'MacBook Pro 16” M5 (16GB / 512GB)',
    category: ['electronics'],
    priceRange: { min: 2200, max: 3300, currency: 'USD' },
    description:
      'Мощная рабочая станция для разработки, видео и звука. Можно дарить в базовой конфигурации или с AppleCare и внешним SSD.',
    variants: [
      'Базовая конфигурация',
      'С AppleCare+',
      'Комплект с внешним NVMe-SSD или док-станцией',
    ],
    priority: 3,
    whereToBuy: [
      'Apple Store или авторизованные реселлеры',
      'Amazon / BestBuy',
      'Магазины электроники в вашем регионе',
    ],
    quantity: 1,
  },
  {
    id: 'f0b350d4-cffe-4ca0-a7de-05388934ba19',
    name: 'Mac mini M5 (32GB / 1TB)',
    category: ['electronics'],
    priceRange: { min: 1000, max: 1900, currency: 'USD' },
    description: 'Компактная, но мощная настольная машина. Идеальна как вторая станция для работы.',
    variants: ['Базовая конфигурация', 'Комплект с монитором', 'Комплект с клавиатурой и мышью'],
    priority: 3,
    whereToBuy: [
      'Apple Store / авторизованные реселлеры',
      'Amazon / BestBuy',
      'Локальные магазины техники',
    ],
    quantity: 1,
  },
  {
    id: 'cb3ce338-3ff7-4590-80f4-d33953eadae4',
    name: 'Valve Steam Machine (новое поколение)',
    category: ['gaming'],
    priceRange: { min: 600, max: 1200, currency: 'USD' },
    description:
      'Новая версия Steam Machine — компактный игровой мини-ПК от Valve на базе SteamOS, разработанный для гостиной.',
    variants: ['512 ГБ NVMe', '2 ТБ NVMe', 'Съёмная лицевая панель (магнитная)'],
    priority: 2,
    whereToBuy: [
      'Steam Store (официальный магазин Valve)',
      'Крупные ритейлеры ПК-железа (Amazon, Newegg)',
      'Магазины мини-ПК и игровых консолей',
    ],
    quantity: 1,
  },
  {
    id: 'ff935e53-5ad6-4e05-9c9f-db78876fa659',
    name: 'Комплект для подкастов',
    category: ['audio', 'streaming'],
    priceRange: { min: 400, max: 2000, currency: 'USD' },
    description:
      'Профессиональный сетап для записи подкастов. Цена зависит от количества каналов и уровня микрофонов.',
    variants: [
      'Интерфейс 2 канала + 2 микрофона',
      'Интерфейс 4 канала + 4 микрофона',
      'Universal Audio / Focusrite профессиональный комплект',
    ],
    priority: 3,
    whereToBuy: [
      'Sweetwater / Thomann / Amazon',
      'Магазины музыкального оборудования',
      'Официальные сайты брендов',
    ],
    quantity: 1,
  },
  {
    id: '6a7c9cbb-e7b1-46cb-aec0-f4686a47c427',
    name: 'Xbox Series X',
    category: ['gaming'],
    priceRange: { min: 450, max: 700, currency: 'USD' },
    description: 'Современная игровая консоль. Отличный подарок для игр и мультимедиа.',
    variants: ['Консоль', 'Консоль + второй контроллер', 'Консоль + Game Pass Ultimate'],
    priority: 3,
    whereToBuy: ['Microsoft Store', 'Amazon / BestBuy / GameStop', 'Местные магазины электроники'],
    quantity: 1,
  },
  {
    id: '66d1e790-0f66-4631-83e0-0beb4294b546',
    name: 'Электронная барабанная установка (универсальная)',
    category: ['electronics', 'music'],
    priceRange: { min: 350, max: 1800, currency: 'USD' },
    description:
      'Электронная барабанная установка — набор электронных падов (снейр, томы, тарелки), бас-пад и модуль/звуковой процессор.',
    variants: ['Alesis Nitro Mesh Kit', 'Yamaha DTX402 / DTX402K', 'Roland TD-07 / TD-07DMK'],
    priority: 2,
    whereToBuy: [
      'Thomann (Europe)',
      'MusicStore / MusicStore (DE)',
      'Местные музыкальные магазины',
    ],
    quantity: 1,
  },
  {
    id: '554d4520-d6f0-46b6-871b-884c0dd05d40',
    name: 'Современный монитор (универсальный, 24–27")',
    category: ['workspace'],
    priceRange: { min: 150, max: 450, currency: 'USD' },
    description:
      'Универсальный современный монитор 24–27" (IPS/VA панель, современный набор входов, опционально USB-C) — простой, надёжный и нейтральный по дизайну.',
    variants: ['24" IPS 1080p, 75Hz', '25–27" 1440p, 75–120Hz', '27" 4K (если нужен высокий DPI)'],
    priority: 1,
    whereToBuy: [
      'Amazon',
      'WinWin / локальные ритейлеры электроники',
      'официальные онлайн-магазины брендов (LG, Dell, Samsung)',
    ],
    quantity: 1,
  },

  {
    id: '5470a157-f7d3-469c-84d5-7d1c95fdbfb0',
    name: 'Универсальное игровое кресло',
    category: ['workspace', 'gaming'],
    priceRange: { min: 150, max: 500, currency: 'USD' },
    description:
      'Эргономичное игровое кресло без конкретного бренда, подходит для работы и игр. Поддержка спины, регулировки высоты и наклона.',
    variants: [
      'Базовая версия',
      'С регулируемыми подлокотниками',
      'Премиум с дополнительной поддержкой поясницы',
    ],
    priority: 1,
    whereToBuy: [
      'Amazon / AliExpress',
      'Локальные магазины мебели и электроники',
      'Официальные магазины универсальных кресел',
    ],
    quantity: 1,
  },
  {
    id: 'e1eced78-e803-469f-b48f-e95cf27a9d22',
    name: 'Stream Deck (Elgato) — Mini / Standard / XL',
    category: ['streaming'],
    priceRange: { min: 80, max: 250, currency: 'USD' },
    description: 'Контроллер для стримов, подкастов и автоматизации. Очень облегчает работу.',
    variants: ['Stream Deck Mini', 'Stream Deck Standard', 'Stream Deck XL'],
    priority: 3,
    whereToBuy: ['Elgato Official Store', 'Amazon / BestBuy', 'Магазины техники для стримеров'],
    quantity: 1,
  },
  {
    id: '9acec396-0625-44c3-b18c-ed57b44147e5',
    name: 'Студийные наушники / мониторы',
    category: ['audio'],
    priceRange: { min: 100, max: 800, currency: 'USD' },
    description:
      'Для подкастов, монтажа, музыки. Закрытые мониторные наушники или небольшие студийные мониторы.',
    variants: [
      'Audio-Technica / Sennheiser / Beyerdynamic',
      'Закрытые мониторные',
      'Настольные студийные мониторы',
    ],
    priority: 1,
    whereToBuy: [
      'Thomann / Sweetwater / Amazon',
      'Магазины музыкального оборудования',
      'Официальные сайты брендов',
    ],
    quantity: 1,
  },
  {
    id: '2efbf0d9-c92c-46d1-8197-54be9204d4d1',
    name: 'USB-микрофон',
    category: ['audio', 'streaming'],
    priceRange: { min: 100, max: 400, currency: 'USD' },
    description:
      'Хорошая альтернатива многоканальному аудиоинтерфейсу — просто подключить и писать.',
    variants: ['Shure MV7', 'Rode NT-USB', 'Blue Yeti X'],
    priority: 3,
    whereToBuy: [
      'Amazon / Sweetwater / Thomann',
      'Магазины музыкального оборудования',
      'Официальные сайты брендов',
    ],
    quantity: 1,
  },
  {
    id: 'c78e3675-f2ff-49a1-af50-e996bbc8cf4c',
    name: 'Виниловые пластинки',
    category: ['music', 'collectibles'],
    priceRange: { min: 20, max: 150, currency: 'USD' },
    description:
      'SOAD, Enter Shikari, Norma Jean, Rammstein — можно дарить любую группу, которую я слушаю.',
    variants: ['Обычное издание', 'Цветная лимитка', 'Редкое переиздание'],
    priority: 2,
    whereToBuy: [
      'Магазины виниловых пластинок',
      'Discogs',
      'Amazon',
      'локальные музыкальные магазины',
    ],
    quantity: 3,
  },
  {
    id: '9485f9b9-012c-49d5-875a-bf0b1158bea7',
    name: 'Винтажный японский бомбер',
    category: ['style', 'clothing'],
    priceRange: { min: 80, max: 350, currency: 'USD' },
    description:
      'Настоящий винтажный японский бомбер, качественный материал, ретро-дизайн. Отличный элемент коллекции или повседневного образа.',
    variants: [
      'Классический бомбер',
      'С вышивкой или патчами',
      'Премиум винтаж (лимитированная серия)',
    ],
    priority: 1,
    whereToBuy: ['Etsy / eBay', 'Винтажные магазины одежды', 'Локальные бутики'],
    quantity: 2,
  },
  {
    id: '321afee6-dd6f-4edf-b2d5-5c7b868de184',
    name: 'Винтажные постеры в рамках',
    category: ['decor', 'collectibles'],
    priceRange: { min: 30, max: 800, currency: 'USD' },
    description: 'Декоративные постеры: репринты, музейное качество, винтажные оригиналы.',
    variants: [
      'Качественный репринт',
      'Постер + декоративная рама',
      'Оригинальный винтажный плакат',
    ],
    priority: 2,
    whereToBuy: [
      'eBay / Etsy / AllPosters',
      'Магазины декора и раритетов',
      'Аукционы винтажных плакатов',
    ],
    quantity: 3,
  },
  {
    id: '44de27f6-6b67-43d1-8c32-9181a672f97c',
    name: 'Игра для Nintendo Switch (например, Blasphemous 2)',
    category: ['gaming'],
    priceRange: { min: 30, max: 60, currency: 'USD' },
    description:
      'Физический картридж или цифровой ключ. Подойдёт любой качественный экшен/метроидвания.',
    variants: ['Blasphemous 2', 'Любая другая игра на усмотрение', 'Коллекционное издание'],
    priority: 1,
    whereToBuy: ['Nintendo eShop', 'Amazon / BestBuy', 'Местные игровые магазины'],
    quantity: 3,
  },
  {
    id: 'f91906e8-cdd3-4575-8170-10f18f42dee5',
    name: 'Красная рубашка в клетку "Lumberjack"',
    category: ['clothing', 'style'],
    priceRange: { min: 35, max: 90, currency: 'USD' },
    description:
      'Плотная фланелевая рубашка в красно-чёрную клетку, классический стиль канадского дровосека. Отлично держит тепло, подходит для работы и повседневной носки.',
    variants: [
      'Классический крой',
      'Slim fit',
      'Regular fit',
      'Длинный рукав с манжетами на пуговицах',
    ],
    priority: 2,
    metadata: {
      style: ['lumberjack', 'casual', 'vintage'],
      preferredMetals: [],
    },
    whereToBuy: ['Patagonia', 'H&M', 'Uniqlo'],
    quantity: 1,
  },
  {
    id: 'a8384ada-d717-4005-9fec-8a57439a8787',
    name: 'Фигурка по Overwatch',
    category: ['collectibles'],
    priceRange: { min: 25, max: 400, currency: 'USD' },
    description:
      'Фигурки персонажей Overwatch: Гендзи, Ханзо, Рейнхард. Массовые или коллекционные.',
    variants: ['Funko Pop', 'Nendoroid', 'Blizzard Collectible Statue'],
    priority: 3,
    whereToBuy: [
      'Blizzard Gear Store',
      'Amazon / eBay / локальные магазины фигурок',
      'Фан-магазины по аниме и играм',
    ],
    quantity: 3,
  },
  {
    id: '57557e1f-7e98-451c-87e4-e96b5ef718af',
    name: 'Фигурка Genex / Kosmaj',
    category: ['collectibles', 'decor'],
    priceRange: { min: 25, max: 200, currency: 'USD' },
    description: 'Фигурка Genex или Kosmaj из бетона.',
    variants: ['Genex', 'Kosmaj'],
    priority: 1,
    whereToBuy: [
      'Местные художественные магазины',
      'Etsy / eBay',
      'Галереи современного искусства',
    ],
    quantity: 2,
  },
  {
    id: 'c9dc7f32-41fc-4f54-bcfc-bbf5f953f622',
    name: 'Аксессуары для костюмов-троек',
    category: ['style', 'clothing'],
    priceRange: { min: 10, max: 250, currency: 'USD' },
    description:
      'Классические аксессуары: уголки на воротник, броши, запонки, зажимы для галстука, лэпел-цепочки, pocket squares.',
    variants: [
      'Уголки для воротника (collar tips)',
      'Брошь или цепочка на лацкан',
      'Зажим для галстука / запонки / набор',
    ],
    metadata: {
      preferredMetals: ['silver', 'steel', 'white gold'],
      style: ['minimalism', 'heroic', 'victorian'],
    },
    priority: 2,
    whereToBuy: [
      'Etsy / Amazon / магазины аксессуаров для костюмов',
      'Локальные бутики мужской одежды',
    ],
    quantity: 1,
  },
  {
    id: 'c9dc7f32-41fc-4f54-bcfc-bbf5f953f622.png',
    name: 'Набор аксессуаров для костюма (комбо-подарок)',
    category: ['style', 'clothing'],
    priceRange: { min: 50, max: 180, currency: 'USD' },
    description:
      'Собранный комплект: брошь + уголки + зажим для галстука + шелковый pocket square.',
    variants: [
      'Минималистичный набор',
      'С декоративной символикой',
      'Премиум (серебро, ручная работа)',
    ],
    priority: 1,
    whereToBuy: ['Etsy / Amazon / локальные магазины аксессуаров', 'Брендовые бутики костюмов'],
    quantity: 1,
  },
  {
    id: 'a2e96e3f-ed50-4a3b-a7c2-8b42591f9388',
    name: 'Домашнее кимоно (лёгкое и удобное)',
    category: ['clothing'],
    priceRange: { min: 40, max: 120, currency: 'USD' },
    description: 'Лёгкое и удобное домашнее кимоно. Материал: хлопок, лен или вискоза.',
    variants: [
      'Льняное простое кимоно',
      'Хлопковое минималистичное кимоно',
      'Лёгкое летнее кимоно (вискоза)',
      'Удлинённый халат-кимоно в тёмном цвете',
    ],
    priority: 2,
    whereToBuy: [
      'Etsy / Amazon / локальные магазины одежды',
      'Бутики японской или минималистичной одежды',
    ],
    quantity: 1,
  },
  {
    id: 'a9e9a2dd-2e7b-4e50-83a3-9cb1fe808715',
    name: 'Книга «Грокаем алгоритмы» — Адитья Бхаргава',
    category: ['books'],
    priceRange: { min: 10, max: 30, currency: 'USD' },
    description: 'Книга о базовых алгоритмах в наглядном и доступном формате.',
    variants: ['Русское издание', 'Английское издание'],
    priority: 2,
    whereToBuy: ['Ozon / Labirint / Amazon', 'Книжные магазины'],
    quantity: 1,
  },
  {
    id: 'ca38c55f-96b6-4677-bd45-ca7d98d203f2',
    name: 'Desk Mat (рабочая поверхность)',
    category: ['workspace'],
    priceRange: { min: 20, max: 80, currency: 'USD' },
    description: 'Поверхность под клавиатуру и мышь, чтобы рабочее место выглядело аккуратнее.',
    variants: ['Фетровый', 'Кожзам', 'Натуральная кожа'],
    priority: 1,
    whereToBuy: ['Amazon / AliExpress / локальные магазины аксессуаров для рабочего места'],
    quantity: 1,
  },
  {
    id: '7a7533d4-b860-40d9-896c-e6fedbcf5a8f',
    name: 'Органайзер для кабелей',
    category: ['workspace'],
    priceRange: { min: 10, max: 40, currency: 'USD' },
    description: 'Набор для аккуратного кабель-менеджмента, чтобы убрать визуальный беспорядок.',
    variants: ['Клипсы', 'Трубки', 'Полный набор для кабель-менеджмента'],
    priority: 1,
    whereToBuy: ['Amazon / AliExpress / магазины электроники'],
    quantity: 1,
  },
  {
    id: '1f7364dc-b092-4e6e-9859-2ea485fa935b',
    name: 'Кольцевая лампа с держателем для смартфона',
    category: ['streaming'],
    priceRange: { min: 20, max: 120, currency: 'USD' },
    description: 'Освещение для стримов и видеозвонков. Полезно, когда света мало.',
    variants: ['Настольная', 'Стойка средняя', 'Профессиональная с регулировкой'],
    priority: 3,
    whereToBuy: ['Amazon / AliExpress / локальные магазины фототехники'],
    quantity: 1,
  },
  {
    id: 'e01ee0b8-7e69-4df5-8a88-699efd28eb6a',
    name: 'Набор стеклянных герметичных контейнеров для кухни',
    category: ['misc'],
    priceRange: { min: 15, max: 60, currency: 'USD' },
    description:
      'Комплект стеклянных контейнеров с силиконовыми крышками — герметичные, подходят для хранения сухих продуктов и остатков.',
    variants: [
      'Набор 3× стеклянных банок (разный объём)',
      'Плоские контейнеры для холодильника',
      'Банки с мерной шкалой',
    ],
    priority: 1,
    whereToBuy: ['IKEA', 'Amazon', 'локальные магазины посуды / хозяйственные магазины'],
    quantity: 2,
  },
  {
    id: 'e3359aee-0611-478e-a413-4d2501a5ec02',
    name: 'Ящик Monster Energy без сахара',
    category: ['misc', 'beverages'],
    priceRange: { min: 25, max: 35, currency: 'USD' },
    description: 'Ящик энергетиков Monster Energy без сахара (12 банок по 500 мл).',
    variants: [
      'Monster Energy Ultra Sunrise',
      'Monster Energy Ultra Red',
      'Monster Energy Ultra Blue',
      'Monster Energy Ultra Black',
    ],
    priority: 1,
    whereToBuy: ['Maxi', 'Idea', 'Metro', 'Delhaize'],
    quantity: 1,
  },
  {
    id: '6a99bafe-a2ad-4f4b-9497-6d3eee20cece',
    name: 'Молотый кофе',
    category: ['misc', 'beverages'],
    priceRange: { min: 6, max: 20, currency: 'USD' },
    description:
      'Классический молотый кофе — удобный и универсальный для ежедневного потребления дома или в офисе.',
    variants: ['250г молотого', '500г молотого'],
    priority: 2,
    whereToBuy: [
      'Amazon.com',
      'Локальные супермаркеты и кофейные магазины в Сербии',
      'Магазины спецкофе',
    ],
    quantity: 1,
  },
  {
    id: 'eca71645-30bf-49ff-91c1-16bf234ed95e',
    name: 'Металлический значок / брелок Overwatch',
    category: ['collectibles'],
    priceRange: { min: 5, max: 25, currency: 'USD' },
    description:
      'Металлический значок или брелок по Overwatch с матовой эмалью — аккуратный аксессуар для коллекции или одежды.',
    variants: ['Маленький значок (pin)', 'Брелок на кольце', 'Лимитированная серия с номером'],
    priority: 1,
    metadata: {
      preferredMetals: ['steel', 'nickel', 'silver'],
      style: ['matte', 'minimal'],
    },
    whereToBuy: ['Blizzard Gear Store', 'Etsy (custom)', 'Amazon / eBay'],
    quantity: 3,
  },
  {
    id: 'd239be3a-32fc-45ea-9450-c1f5b94ccd6f',
    name: 'Помощь в отбитии трат на день рождения',
    category: ['contribution'],
    priceRange: { min: 1, max: 9999, currency: 'USD' },
    description: 'Финансовая помощь на празднование. Можно перевести любую сумму.',
    variants: ['Банковский перевод', 'Подарочная карта', 'Любая сумма'],
    priority: 0,
    whereToBuy: ['Любой способ перевода денег'],
    quantity: 99,
  },
  {
    id: '33ae564f-e4c3-49b2-8027-21c78256d37c',
    name: 'Подарок на усмотрение дарителя',
    category: ['misc'],
    priceRange: { min: 1, max: 9999, currency: 'USD' },
    description: 'Если вы уверены, что это мне нужно — смело берите. Я люблю сюрпризы.',
    variants: ['Что угодно'],
    priority: 0,
    whereToBuy: ['Любой магазин или источник'],
    quantity: 99,
  },
  {
    id: 'bf987e71-365b-4e97-a6d5-85e16e1d0e44',
    name: 'Выступление Артёма Андреева',
    category: ['misc'],
    priceRange: { min: 1, max: 9999, currency: 'USD' },
    description: 'Выступление стендап-комика Артёма Андреева ',
    variants: ['Короткий корпоративный сет (15–20 мин)'],
    priority: 2,
    whereToBuy: ['Прямой контакт через соцсети Артёма'],
    quantity: 1,
  },
];

export default function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Content-Type', 'application/json');
  res.status(200).json(wishlist);
}
